Integration tests fail if no 'safe to test' label
highfidelity/hifi-spatial-audio-js pull request #143
Opened 2021-06-24 22:46 UTC by RebeccaStankus

2021-06-24 23:14 UTC, hd23408 requested changes

2021-06-24 23:14 UTC, hd23408 commented on .github/workflows/run-unit-tests.yml
> +        description: "Host name, i.e. 'api.highfidelity.com', `api-staging-latest.highfidelity.com`, or 'api-pro-east.highfidelity.com'"
Do unit tests require a stack name?

2021-06-25 19:00 UTC, RebeccaStankus commented on .github/workflows/run-unit-tests.yml
> +        description: "Host name, i.e. 'api.highfidelity.com', `api-staging-latest.highfidelity.com`, or 'api-pro-east.highfidelity.com'"
oh, good catch...no they don't!

2021-07-01 19:01 UTC, joy-highfidelity approved these changes
✅

2021-07-01 19:06 UTC, hd23408 approved these changes

2021-07-01 19:06 UTC, merged